# Generated by Django 2.2.1 on 2022-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220716_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('cart_id', models.CharField(default='to_be_assigned', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_no', models.CharField(default='N/A', max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=10)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
