# Generated by Django 2.2.1 on 2022-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220716_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='image',
            field=models.TextField(default='user_profile/default.png', max_length=150),
        ),
    ]
