# Generated by Django 2.2.1 on 2022-07-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_item_tot_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='tot_price',
            new_name='total_price',
        ),
    ]
