# Generated by Django 4.0.3 on 2022-07-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220716_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_generator',
            name='total_of_cart',
            field=models.IntegerField(default=0),
        ),
    ]
